# Default Postgres configuration for local environments.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: aa13567834566a
  variables:
    statement_timeout: <%= ENV.fetch("DB_STATEMENT_TIMEOUT", 5000) %>

development:
  <<: *default
  database: menumate_development

test:
  <<: *default
  database: menumate_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["CACHE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["QUEUE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
